config/routes.rb
Rails.application.routes.draw do
  resources :globalcontacts

  resources :contacts

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "terms" => "pages#terms"
  get "contacts" => "pages#contacts"
  get "globalcontacts" => "pages#globalcontacts"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :user
	belongs_to :globalcontact
end

app/models/globalcontact.rb
class Globalcontact < ActiveRecord::Base
	has_many :contacts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :firstname
   devise_parameter_sanitizer.for(:account_update) << :firstname
   devise_parameter_sanitizer.for(:sign_up) << :lastname
   devise_parameter_sanitizer.for(:account_update) << :lastname
 end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:globalID, :points)
    end
end

app/controllers/globalcontacts_controller.rb
class GlobalcontactsController < ApplicationController
  before_action :set_globalcontact, only: [:show, :edit, :update, :destroy]

  # GET /globalcontacts
  # GET /globalcontacts.json
  def index
    @globalcontacts = Globalcontact.all
  end

  # GET /globalcontacts/1
  # GET /globalcontacts/1.json
  def show
  end

  # GET /globalcontacts/new
  def new
    @globalcontact = Globalcontact.new
  end

  # GET /globalcontacts/1/edit
  def edit
  end

  # POST /globalcontacts
  # POST /globalcontacts.json
  def create
    @globalcontact = Globalcontact.new(globalcontact_params)

    respond_to do |format|
      if @globalcontact.save
        format.html { redirect_to @globalcontact, notice: 'Globalcontact was successfully created.' }
        format.json { render :show, status: :created, location: @globalcontact }
      else
        format.html { render :new }
        format.json { render json: @globalcontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /globalcontacts/1
  # PATCH/PUT /globalcontacts/1.json
  def update
    respond_to do |format|
      if @globalcontact.update(globalcontact_params)
        format.html { redirect_to @globalcontact, notice: 'Globalcontact was successfully updated.' }
        format.json { render :show, status: :ok, location: @globalcontact }
      else
        format.html { render :edit }
        format.json { render json: @globalcontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /globalcontacts/1
  # DELETE /globalcontacts/1.json
  def destroy
    @globalcontact.destroy
    respond_to do |format|
      format.html { redirect_to globalcontacts_url, notice: 'Globalcontact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_globalcontact
      @globalcontact = Globalcontact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def globalcontact_params
      params.require(:globalcontact).permit(:firstname, :lastname, :email, :twitterid, :linkedin, :facebook)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/globalcontacts_helper.rb
module GlobalcontactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :globalID %><br>
    <%= f.number_field :globalID %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Globalid</th>
      <th>First Name</th>
      <th>Points</th>
      <th>User_ID</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td>
        <% 

        %>
        <%= %>
        </td>
        <td><%= contact.globalID %></td>
        <td><%= contact.points %></td>
        <td><%= contact.user_id %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Globalid:</strong>
  <%= @contact.globalID %>
</p>

<p>
  <strong>Points:</strong>
  <%= @contact.points %>
</p>

<p>
  <strong>UserID:</strong>
  <%= @contact.user_id %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/globalcontacts/_form.html.erb
<%= form_for(@globalcontact) do |f| %>
  <% if @globalcontact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@globalcontact.errors.count, "error") %> prohibited this globalcontact from being saved:</h2>

      <ul>
      <% @globalcontact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :twitterid %><br>
    <%= f.text_field :twitterid %>
  </div>
  <div class="field">
    <%= f.label :linkedin %><br>
    <%= f.text_field :linkedin %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/globalcontacts/edit.html.erb
<h1>Editing globalcontact</h1>

<%= render 'form' %>

<%= link_to 'Show', @globalcontact %> |
<%= link_to 'Back', globalcontacts_path %>

app/views/globalcontacts/index.html.erb
<h1>Listing globalcontacts</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Twitterid</th>
      <th>Linkedin</th>
      <th>Facebook</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @globalcontacts.each do |globalcontact| %>
      <tr>
        <td><%= globalcontact.firstname %></td>
        <td><%= globalcontact.lastname %></td>
        <td><%= globalcontact.email %></td>
        <td><%= globalcontact.twitterid %></td>
        <td><%= globalcontact.linkedin %></td>
        <td><%= globalcontact.facebook %></td>
        <td><%= link_to 'Show', globalcontact %></td>
        <td><%= link_to 'Edit', edit_globalcontact_path(globalcontact) %></td>
        <td><%= link_to 'Destroy', globalcontact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Globalcontact', new_globalcontact_path %>

app/views/globalcontacts/new.html.erb
<h1>New globalcontact</h1>

<%= render 'form' %>

<%= link_to 'Back', globalcontacts_path %>

app/views/globalcontacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @globalcontact.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @globalcontact.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @globalcontact.email %>
</p>

<p>
  <strong>Twitterid:</strong>
  <%= @globalcontact.twitterid %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @globalcontact.linkedin %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @globalcontact.facebook %>
</p>

<%= link_to 'Edit', edit_globalcontact_path(@globalcontact) %> |
<%= link_to 'Back', globalcontacts_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "Nurture Up", root_path, class: "navbar-brand"%>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <% if user_signed_in? %>
          <li><%= link_to "My Account", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-end -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nurture Up</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header'%>
	<div class="container">
		<% flash.each do |name, msg| %>
     		<%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>
		<%= yield %>
	</div>

   <div class="footer">
      <div class="container">
        <h5>Copyright Nurture Up. All Rights Reserved. <%= link_to "Terms.", terms_path %> Contact. Meet Our Team.</h5>
      </div>
   </div>

 </body>

app/views/pages/about.html.erb
<h1> about us </h1>
<p> we are workign on our one month rails project pinterestin app</p>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Work your Network</h1>
	
	<% if user_signed_in? %>
		<%= link_to "My contacts", contacts_path %> </br>
		<%= link_to "My contacts details", globalcontacts_path %>
	<% else %>
	<p>Click here to <%=link_to "Sign Up", new_user_registration_path, class: "btn btn-primary"%></p>
	<small>Already signed up? <%=link_to "Login", new_user_session_path%></small>
	<% end %>

</div>

app/views/pages/terms.html.erb
<h2>Terms and Conditions</h2>


<h3>In using this website you are deemed to have read and agreed to the following terms and conditions:</h3>

<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and any or all Agreements: "Client", “You” and “Your” refers to you, the person accessing this website and accepting the Company’s terms and conditions. "The Company", “Ourselves”, “We” and "Us", refers to our Company. “Party”, “Parties”, or “Us”, refers to both the Client and ourselves, or either the Client or ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner, whether by formal meetings of a fixed duration, or any other means, for the express purpose of meeting the Client’s needs in respect of provision of the Company’s stated services/products, in accordance with and subject to, prevailing English Law. Any use of the above terminology or other words in the singular, plural, capitalisation and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>


<p class=lead>Privacy Statement</p>
<p>
We are committed to protecting your privacy. Authorized employees within the company on a need to know basis only use any information collected from individual customers. We constantly review our systems and data to ensure the best possible service to our customers. Parliament has created specific offences for unauthorised actions against computer systems and data. We will investigate any such actions with a view to prosecuting and/or taking civil proceedings to recover damages against those responsible
</p>


<p class=lead>Confidentiality</p>
<p>
We are registered under the Data Protection Act 1998 and as such, any information concerning the Client and their respective Client Records may be passed to third parties. However, Client records are regarded as confidential and therefore will not be divulged to any third party, other than [our manufacturer/supplier(s) and] if legally required to do so to the appropriate authorities. Clients have the right to request sight of, and copies of any and all Client Records we keep, on the proviso that we are given reasonable notice of such a request. Clients are requested to retain copies of any literature issued in relation to the provision of our services. Where appropriate, we shall issue Client’s with appropriate written information, handouts or copies of records as part of an agreed contract, for the benefit of both parties.

We will not sell, share, or rent your personal information to any third party or use your e-mail address for unsolicited mail. Any emails sent by this Company will only be in connection with the provision of agreed services and products.
</p>


<p class=lead>Disclaimer</p>
<p>
Exclusions and Limitations 
The information on this web site is provided on an "as is" basis. To the fullest extent permitted by law, this Company:
•	excludes all representations and warranties relating to this website and its contents or which is or may be provided by any affiliates or any other third party, including in relation to any inaccuracies or omissions in this website and/or the Company’s literature; and 
•	excludes all liability for damages arising out of or in connection with your use of this website. This includes, without limitation, direct loss, loss of business or profits (whether or not the loss of such profits was foreseeable, arose in the normal course of things or you have advised this Company of the possibility of such potential loss), damage caused to your computer, computer software, systems and programs and the data thereon or any other direct or indirect, consequential and incidental damages. 
This Company does not however exclude liability for death or personal injury caused by its negligence. The above exclusions and limitations apply only to the extent permitted by law. None of your statutory rights as a consumer are affected. 
</p>